require("dotenv").config();
const express = require("express");
require("./src/config/database");
const userRoutes = require("./src/routes/userRoutes");
const trabalhoRoutes = require("./src/routes/trabalhoRoutes");
const errorHandler = require("./src/middlewares/errorHandler");
const uploadRoutes = require("./src/routes/uploadRoutes");
const arquivoRoutes = require("./src/routes/arquivoRoutes");
const authRoutes = require("./src/routes/authRoutes");
const errorMiddleware = require("./src/middlewares/errorMiddleware");
const app = express();
app.use(express.json());
app.use(uploadRoutes);
app.use(arquivoRoutes);
app.use(userRoutes);
app.use(trabalhoRoutes);
app.use(authRoutes);
app.use(errorMiddleware);
const PORT = 3000;
app.listen(PORT, function () {
    console.log(`Servidor rodando na porta ${PORT}`);
});